service: crud-ts-sls
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

plugins: 
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-tscpaths
  

functions:
  buscarTodosUsuarios:
    handler: ./src/index.buscar
    events:
      - httpApi:
          path: /buscar/usuarios
          method: get
          
  cadastrarUsuario:
      handler: ./src/index.criar
      events:
        - httpApi:
            path: /criar/usuario
            method: post

  atualizarUsuario:
      handler: ./src/index.atualizar
      events:
        - httpApi:
            path: /atualizar/usuario
            method: patch

  deletarUsuario:
      handler: ./src/index.deletar
      events:
        - httpApi:
            path: /deletar/usuario
            method: delete         